version: "3.9"
services:
  web:
    build: ./api_server
    volumes:
      - ./api_server:/api_server
      - ./node_modules:/api_server/node_modules
    ports:
      - 8000:1234
    env_file: ./api_server/.env.development
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_styled_components_practice
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - ./api_server/app/swagger:/frontend/swagger
    command: sh -c "npm run dev"
    container_name: frontend
    ports:
      - 3001:3000
    env_file: ./frontend/.env.development
    restart: always
    tty: true
    stdin_open: true
